version: "3.5"

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - microquiz

networks:
  microquiz:
    name: microquiz-network
    external: true